version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  backend:
    env_file: .env
    image: helgg/kittygram_backend
    depends_on:
      - db
    volumes:
      - static:/app/collected_static/
      - media:/app/media
  frontend:
    image: helgg/kittygtram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: helgg/kittygtram_gateway
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
